# Generated by Django 5.0.7 on 2024-08-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_subscription_course_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
